version: '2'

services:
  front-end:
    image: palinko/front-end
    hostname: localhost
    ports:
      - "8079:8079"
    restart: always
    cap_drop:
      - all
    read_only: true
  catalogue:
    image: palinko/catalogue
    hostname: localhost
    ports:
      - "3002:3002"
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    depends_on:
      - db
    environment:
      - DATABASE_HOST=localhost
  db:
    image: palinko/db
    hostname: localhost
    ports:
      - "3306:3306"
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=shop
  carts:
    image: palinko/carts
    hostname: localhost
    ports:
      - "3002:3002"
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    environment:
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  orders:
    image: palinko/orders
    hostname: localhost
    ports:
      - "3004:3004"
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    tmpfs:
      - /tmp:rw,noexec,nosuid
    depends_on:
      - db
    environment:
      - DATABASE_HOST=localhost
      - JAVA_OPTS=-Xms64m -Xmx128m -XX:PermSize=32m -XX:MaxPermSize=64m -XX:+UseG1GC -Djava.security.egd=file:/dev/urandom
  user:
    image: palinko/user
    hostname: localhost
    ports:
      - "3001:3001"
    restart: always
    cap_drop:
      - all
    cap_add:
      - NET_BIND_SERVICE
    read_only: true
    depends_on:
      - db
    environment:
      - DATABASE_HOST=localhost
    command: "-d 60 -r 200 -c 2 -h front-end"
