language: go
sudo: required
services:
  - docker
install: true

env:
  - GROUP=shopmicroservice COMMIT=$TRAVIS_COMMIT TAG=$TRAVIS_TAG REPO=edge-router;

script:
  - set -e
  - docker build -t ${GROUP}/${REPO}:${COMMIT} .

after_success:
  - set -e;
  - if [ -z "$DOCKER_PASS" ] ; then
      echo "This is a build triggered by an external PR. Skipping docker push.";
      exit 0;
    fi;
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS;
  - ./push.sh
